### ISSUE TITLE
As a Kearney development team, we need to have a roadmap of the timing to set up each environment.

### ISSUE THREAD

**Issue by drewleety** [18F/data-act-usaspending#91]
Acceptance Criteria:  
- [ ] Develop a list of components required 
- [ ] Draft any alternatives 
- [ ] Obtain concurrence with OCIO office on proposed architecture
